#!/usr/bin/env bash
# Start Circle on this machine.
#
# Creates the virtualenv on first run, installs dependencies, builds the web
# UI, then starts the server on localhost. Everything private stays here: this
# script never uploads anything.
set -euo pipefail

# This script lives in backend/scripts/, but requirements.txt, .env, the
# virtualenv and ../frontend all belong to backend/. Resolve that first, so a
# run from anywhere (or from inside scripts/) still finds them.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
FRONTEND_DIR="$(cd "$BACKEND_DIR/../frontend" && pwd)"
cd "$BACKEND_DIR"

PORT="${PORT:-8000}"

# Prefer a Python that actually reports 3.11+. On Windows `python3` is often a
# Microsoft Store stub that opens the store instead of running, so checking
# the version is the only reliable test.
pick_python() {
  local cand
  for cand in "${PYTHON:-}" python3 python; do
    [ -n "$cand" ] || continue
    if command -v "$cand" >/dev/null 2>&1 &&
       "$cand" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 11) else 1)' \
         >/dev/null 2>&1; then
      printf '%s\n' "$cand"
      return 0
    fi
  done
  return 1
}

PY="$(pick_python || true)"
if [ -z "$PY" ]; then
  echo "Python 3.11 or newer is required, but none was found on PATH."
  echo "Install it from python.org and tick 'Add Python to PATH'."
  exit 1
fi

if [ ! -d .venv ]; then
  echo "Creating the Python environment (first run only)..."
  "$PY" -m venv .venv
fi

# Use the venv's interpreter directly rather than `activate`, which needs a
# different path on Windows and silently falls through if it is missing.
VENV_PY="$BACKEND_DIR/.venv/bin/python"
[ -x "$VENV_PY" ] || VENV_PY="$BACKEND_DIR/.venv/Scripts/python.exe"
if [ ! -x "$VENV_PY" ]; then
  echo "The virtualenv at .venv looks incomplete. Delete it and run this again."
  exit 1
fi

if [ ! -f .installed ]; then
  echo "Installing dependencies (first run only)..."
  "$VENV_PY" -m pip install --upgrade pip >/dev/null
  "$VENV_PY" -m pip install -r requirements.txt
  : > .installed
fi

if [ ! -f "$FRONTEND_DIR/dist/index.html" ]; then
  echo "Building the web interface (first run only)..."
  if command -v npm >/dev/null 2>&1; then
    (cd "$FRONTEND_DIR" && npm install && npm run build)
  else
    echo "npm was not found, so the interface cannot be built."
    echo "Install Node 18+ from nodejs.org, then run this again."
    exit 1
  fi
fi

# Check the prerequisites before starting. A missing MongoDB or a model that
# was never pulled otherwise shows up as a UI where nothing works, which reads
# as "Circle is broken". Print the exact fix instead. CIRCLE_SKIP_DOCTOR=1
# starts anyway (useful for a managed deployment that checks health itself).
if [ -z "${CIRCLE_SKIP_DOCTOR:-}" ]; then
  if ! "$VENV_PY" "$SCRIPT_DIR/doctor.py"; then
    echo "Circle is not ready to start yet. Fix the items above, then run this again."
    echo "To start anyway, set CIRCLE_SKIP_DOCTOR=1."
    exit 1
  fi
fi

# A shared key is generated automatically so that if the user later exposes
# this machine through a tunnel, the archive is not readable by anyone who
# finds the URL. It lives in .env, which is gitignored. Generated with Python
# so it works the same on every platform (no /dev/urandom assumption).
if [ ! -f .env ]; then
  KEY="$("$VENV_PY" -c 'import secrets,string; print("".join(secrets.choice(string.ascii_letters+string.digits) for _ in range(24)))')"
  cat > .env <<EOF
# Generated by serve.sh. Keep this file private.
ACCESS_KEY=$KEY
ALLOW_REMOTE=true
# Add your Render URL here so the hosted UI may call this API:
# CORS_ORIGINS=https://your-app.onrender.com
EOF
  echo
  echo "Your access key has been written to backend/.env"
fi

# Read just the key back for display. Do not `source` .env: a user-edited value
# can contain characters the shell would try to interpret.
KEY="$(grep -E '^ACCESS_KEY=' .env 2>/dev/null | tail -1 | cut -d= -f2- || true)"
if [ -n "${KEY:-}" ]; then
  echo
  echo "  Access key: $KEY"
  echo "  (needed whenever you open Circle from another device)"
fi

echo
echo "Starting Circle on http://127.0.0.1:$PORT"
echo "Open that address in your browser."
echo
echo "To open Circle from another device, run this in a second terminal:"
echo "  cloudflared tunnel --url http://127.0.0.1:$PORT"
echo "then paste the address it prints into the app."
echo

# Open the browser once the server answers, so the first thing the user sees is
# Circle rather than a connection error. The helper waits and then opens;
# set CIRCLE_NO_BROWSER=1 to skip it (CI, a server with no desktop).
if [ -z "${CIRCLE_NO_BROWSER:-}" ]; then
  "$VENV_PY" "$SCRIPT_DIR/wait_and_open.py" "http://127.0.0.1:$PORT" &
fi

exec "$VENV_PY" -m uvicorn circle.main:app --host 127.0.0.1 --port "$PORT"
