@echo off
REM Start Circle on this machine.
REM
REM Creates the virtualenv on first run, installs dependencies, builds the web
REM UI, then starts the server on localhost. Nothing is uploaded anywhere.
setlocal enabledelayedexpansion

REM This file lives in backend\scripts\, but requirements.txt, .env, the
REM virtualenv and ..\frontend all belong to backend\. Move there first so a
REM double-click or a run from any directory still finds them.
cd /d "%~dp0.."
set "BACKEND_DIR=%CD%"
set "FRONTEND_DIR=%BACKEND_DIR%\..\frontend"
if "%PORT%"=="" set "PORT=8000"

REM `where python` can succeed on the Microsoft Store stub, which opens the
REM store instead of running. Check the version too.
set "PY="
for %%P in (python py) do (
  if not defined PY (
    %%P -c "import sys; raise SystemExit(0 if sys.version_info >= (3,11) else 1)" >nul 2>nul
    if not errorlevel 1 set "PY=%%P"
  )
)
if not defined PY (
  echo Python 3.11 or newer is required. Install it from python.org
  echo and tick "Add Python to PATH" during setup.
  pause
  exit /b 1
)

if not exist .venv (
  echo Creating the Python environment ^(first run only^)...
  %PY% -m venv .venv
  if errorlevel 1 (
    echo Could not create the virtualenv. Delete the .venv folder and retry.
    pause
    exit /b 1
  )
)

set "VENV_PY=%BACKEND_DIR%\.venv\Scripts\python.exe"
if not exist "%VENV_PY%" (
  echo The virtualenv at .venv looks incomplete. Delete it and run this again.
  pause
  exit /b 1
)

if not exist .installed (
  echo Installing dependencies ^(first run only^)...
  "%VENV_PY%" -m pip install --upgrade pip >nul
  "%VENV_PY%" -m pip install -r requirements.txt
  if errorlevel 1 (
    echo Dependency install failed. See the messages above.
    pause
    exit /b 1
  )
  echo ok> .installed
)

if not exist "%FRONTEND_DIR%\dist\index.html" (
  echo Building the web interface ^(first run only^)...
  where npm >nul 2>nul
  if errorlevel 1 (
    echo npm was not found, so the interface cannot be built.
    echo Install Node 18+ from nodejs.org, then run this again.
    pause
    exit /b 1
  )
  pushd "%FRONTEND_DIR%"
  call npm install
  call npm run build
  if errorlevel 1 (
    popd
    echo Interface build failed. See the messages above.
    pause
    exit /b 1
  )
  popd
)

REM Check the prerequisites before starting. A missing MongoDB or a model that
REM was never pulled otherwise shows up as a UI where nothing works, which
REM reads as "Circle is broken". Print the exact fix instead.
REM CIRCLE_SKIP_DOCTOR=1 starts anyway.
if not defined CIRCLE_SKIP_DOCTOR (
  "%VENV_PY%" "%~dp0doctor.py"
  if errorlevel 1 (
    echo Circle is not ready to start yet. Fix the items above, then run this again.
    echo To start anyway, set CIRCLE_SKIP_DOCTOR=1.
    pause
    exit /b 1
  )
)

REM A shared key is generated automatically so that if this machine is later
REM exposed through a tunnel, the archive is not readable by anyone who finds
REM the URL. .env is gitignored. Generated with the venv Python so the same
REM code path is used on every platform.
if not exist .env (
  echo.
  echo Generating an access key...
  "%VENV_PY%" -c "import secrets,string,pathlib;a=''.join(secrets.choice(string.ascii_letters+string.digits) for _ in range(24));pathlib.Path('.env').write_text('# Generated by serve.bat. Keep this file private.\nACCESS_KEY='+a+'\nALLOW_REMOTE=true\n# Add your Render URL here so the hosted UI may call this API:\n# CORS_ORIGINS=https://your-app.onrender.com\n');print('  Access key: '+a)"
)

REM Show the key without echoing the whole file. Do not `set` from the file:
REM a value with spaces or quotes would corrupt the environment.
for /f "tokens=1,* delims==" %%A in ('findstr /b "ACCESS_KEY=" .env 2^>nul') do set "KEY=%%B"
if defined KEY (
  echo.
  echo   Access key: !KEY!
  echo   ^(needed whenever you open Circle from another device^)
)

echo.
echo Starting Circle on http://127.0.0.1:%PORT%
echo Open that address in your browser.
echo.
echo To open Circle from another device, run this in a second terminal:
echo   cloudflared tunnel --url http://127.0.0.1:%PORT%
echo then paste the address it prints into the app.
echo.

REM Open the browser only once the server answers, so the user sees Circle
REM instead of a connection error. The helper waits then opens; set
REM CIRCLE_NO_BROWSER=1 to skip.
if not defined CIRCLE_NO_BROWSER (
  start "" /b "%VENV_PY%" "%~dp0wait_and_open.py" http://127.0.0.1:%PORT%
)

"%VENV_PY%" -m uvicorn circle.main:app --host 127.0.0.1 --port %PORT%
endlocal
