@echo off
REM Start Circle on this machine.
REM
REM Creates the virtualenv on first run, installs dependencies, builds the web
REM UI, then starts the server on localhost. Nothing is uploaded anywhere.
setlocal
cd /d "%~dp0"

where python >nul 2>nul
if errorlevel 1 (
  echo Python 3.11 or newer is required. Install it from python.org
  echo and tick "Add Python to PATH" during setup.
  pause
  exit /b 1
)

if not exist .venv (
  echo Creating the Python environment ^(first run only^)...
  python -m venv .venv
)
call .venv\Scripts\activate.bat

if not exist .installed (
  echo Installing dependencies ^(first run only^)...
  python -m pip install --upgrade pip >nul
  python -m pip install -r requirements.txt
  echo ok> .installed
)

if not exist ..\frontend\dist\index.html (
  echo Building the web interface ^(first run only^)...
  pushd ..\frontend
  call npm install
  call npm run build
  popd
)

REM A shared key is generated automatically so that if this machine is later
REM exposed through a tunnel, the archive is not readable by anyone who finds
REM the URL. .env is gitignored.
if not exist .env (
  echo.
  echo Generating an access key...
  python -c "import secrets,string,pathlib;a=''.join(secrets.choice(string.ascii_letters+string.digits) for _ in range(24));pathlib.Path('.env').write_text('# Generated by serve.bat. Keep this file private.\nACCESS_KEY='+a+'\nALLOW_REMOTE=true\n# Add your Render URL here so the hosted UI may call this API:\n# CORS_ORIGINS=https://your-app.onrender.com\n');print('  Access key: '+a)"
)

echo.
echo Starting Circle on http://127.0.0.1:8000
echo Open that address in your browser.
echo.
echo To open Circle from another device, run this in a second terminal:
echo   cloudflared tunnel --url http://127.0.0.1:8000
echo then paste the address it prints into the app.
echo.

start "" http://127.0.0.1:8000
python -m uvicorn circle.main:app --host 127.0.0.1 --port 8000
endlocal