#!/usr/bin/env bash
# Start Circle on this machine.
#
# Creates the virtualenv on first run, installs dependencies, builds the web
# UI, then starts the server on localhost. Everything private stays here: this
# script never uploads anything.
set -euo pipefail

cd "$(dirname "$0")"

PY="${PYTHON:-python3}"
command -v "$PY" >/dev/null 2>&1 || PY=python
command -v "$PY" >/dev/null 2>&1 || { echo "Python 3.11+ is required."; exit 1; }

if [ ! -d .venv ]; then
  echo "Creating the Python environment (first run only)..."
  "$PY" -m venv .venv
fi
# shellcheck disable=SC1091
. .venv/bin/activate 2>/dev/null || . .venv/Scripts/activate

if [ ! -f .installed ]; then
  echo "Installing dependencies (first run only)..."
  pip install --upgrade pip >/dev/null
  pip install -r requirements.txt
  touch .installed
fi

if [ ! -f ../frontend/dist/index.html ]; then
  echo "Building the web interface (first run only)..."
  (cd ../frontend && npm install && npm run build)
fi

# A shared key is generated automatically so that if the user later exposes
# this machine through a tunnel, the archive is not readable by anyone who
# finds the URL. It lives in .env, which is gitignored.
if [ ! -f .env ]; then
  KEY="$(head -c 24 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 24)"
  cat > .env <<EOF
# Generated by serve.sh. Keep this file private.
ACCESS_KEY=$KEY
ALLOW_REMOTE=true
# Add your Render URL here so the hosted UI may call this API:
# CORS_ORIGINS=https://your-app.onrender.com
EOF
  echo
  echo "Your access key has been written to backend/.env"
fi

# shellcheck disable=SC1091
. ./.env 2>/dev/null || true
KEY="${ACCESS_KEY:-}"
if [ -n "$KEY" ]; then
  echo
  echo "  Access key: $KEY"
  echo "  (needed whenever you open Circle from another device)"
fi

echo
echo "Starting Circle on http://127.0.0.1:8000"
echo "Open that address in your browser."
echo
echo "To open Circle from another device, run this in a second terminal:"
echo "  cloudflared tunnel --url http://127.0.0.1:8000"
echo "then paste the address it prints into the app."
echo

exec python -m uvicorn circle.main:app --host 127.0.0.1 --port "${PORT:-8000}"